### ISSUE TITLE
missing data in settings ?

### ISSUE THREAD

**Issue by bishem** [Lukas22041/Random-Assortment-of-Things#10]
i don't know if you encountered that error already but figured it would not hurt to say something
it does not crash the game at start at least but i get this error

```log
146793 [Thread-2] INFO  org.magiclib.achievements.MagicAchievementManager  - [{"image":"","spoilerLevel":"SPOILER","name":"Stared Back","tooltip":"","description":"Defeated the singularity at the bottom of the abyss.","id":"rat_beatSingularity","script":"assortment_of_things.achivements.DefeatedSingularityAchivement","rarity":"LEGENDARY"},{"image":"","spoilerLevel":"SPOILER","name":"Angel of the Abyss","tooltip":"","description":"Defeated the challenge version of the singularity encounter.","id":"rat_beatSingularityChallenge","script":"assortment_of_things.achivements.DefeatedSingularityAchivement","rarity":"LEGENDARY"},{"image":"","spoilerLevel":"","name":"","tooltip":"","description":"","id":"","script":"","rarity":""},{"image":"","spoilerLevel":"SPOILER","name":"Interstellar","tooltip":"","description":"Completed the main Exotech Questline. Unlocks the \"Personal Exoship\" Background.","id":"rat_beatExotechQuestline","script":"assortment_of_things.achivements.RATBaseAchievement","rarity":"LEGENDARY"}]
146835 [Thread-2] WARN  org.magiclib.achievements.MagicAchievementManager  - Invalid rarity ' for achievement '', using Common.
146862 [Thread-2] WARN  org.magiclib.achievements.MagicAchievementManager  - Unable to load achievement '' because class '' didn't load!
java.lang.ClassNotFoundException:
        at org.codehaus.janino.JavaSourceClassLoader.findClass(JavaSourceClassLoader.java:183) ~[janino-3.0.12.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at org.magiclib.achievements.MagicAchievementManager.generateAchievementsFromSpec(MagicAchievementManager.java:399) ~[?:?]
        at org.magiclib.achievements.MagicAchievementManager.reloadAchievements(MagicAchievementManager.java:291) ~[?:?]
        at org.magiclib.achievements.MagicAchievementManager.setAchievementsEnabled(MagicAchievementManager.java:141) ~[?:?]
        at org.magiclib.achievements.MagicAchievementManager.onApplicationLoad(MagicAchievementManager.java:116) ~[?:?]
        at org.magiclib.Magic_modPlugin.onApplicationLoad(Magic_modPlugin.java:75) ~[?:?]
        at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source) ~[port_obf.jar:?]
        at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

if it crashes at some point mid-game i will let you know, if you want me to that is

**Comment by bishem** [comment]
here is my mod list if it helps, i am seeing no compatibility issue so far

```json
{
  "enabledMods": [
    "CaptainsLog",
    "lw_radar",
    "fleethistory",
    "fleet_journal",
    "particleengine",
    "timid_tmi",
    "transfer_all_items",
    "variants_lib",
    "which_industry",
    "whichmod",
    "whichtmi",
    "aaacrew_replacer",
    "Rouge_Redstar",
    "sun_fuel_siphoning",
    "lw_lazylib",
    "lunalib",
    "MagicLib",
    "RetroLib",
    "shaderLib",
    "stelnet",
    "lw_console",
    "player_portraits_extended",
    "portrait_changer",
    "more_character_portraits_vanilla",
    "more_character_portraits_mods",
    "more_character_portraits",
    "immersionFriendlyPortraitPack",
    "hostileIntercept",
    "largerZoomOut",
    "speedUp",
    "nexerelin",
    "Planetace_AstralAscension",
    "IndEvo",
    "GrandColonies",
    "pantera_ANewLevel40R",
    "lw_autosave",
    "timid_admins",
    "dynamictariffs",
    "diyplanets",
    "timid_cum",
    "progressiveSMods",
    "QualityCaptains",
    "logisticsNotifications",
    "US",
    "officerExtension",
    "fleetsizebydp",
    "guarantee-rare-items",
    "more_procgen_names",
    "more_ship_names",
    "planet_search",
    "leadingPip",
    "WEAPONARCS",
    "chatter",
    "illustrated_entities",
    "sun_new_beginnings",
    "More_Ai_Core_Skills",
    "wyv_planetaryShieldAccessControl",
    "scan_those_gates",
    "pt_qolpack",
    "sun_starship_legends",
    "aitweaks",
    "assortment_of_things"
  ]
}
```
